version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0

  client:
    image: node:alpine
    build: ./web
    command: pnpm vite
    volumes:
      - ./web:/usr/src/app
    ports:
      - 8000:8000
    tty: true

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
